"""authoritative sqlite persistence schema

Revision ID: 4ab3b3b323b6
Revises: 0001_initial_baseline
Create Date: 2026-10-02 15:03:22.543354
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4ab3b3b323b6'
down_revision: Union[str, None] = '0001_initial_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handover_packets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handover_packets'))
    )
    with op.batch_alter_table('handover_packets', schema=None) as batch_op:
        batch_op.create_index('ix_handover_packets_acknowledged_at', ['acknowledged_at'], unique=False)
        batch_op.create_index('ix_handover_packets_created_at', ['created_at'], unique=False)

    op.create_table('machines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machines'))
    )
    op.create_table('sync_changes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_changes'))
    )
    op.create_table('sync_conflicts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_conflicts'))
    )
    op.create_table('verification_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_rules'))
    )
    op.create_table('components',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('machine_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_components_machine_id_machines'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_components')),
    sa.UniqueConstraint('id', 'machine_id', name='uq_components_id_machine_id')
    )
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.create_index('ix_components_machine_id', ['machine_id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('machine_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'VERIFYING', 'VERIFIED', 'RECURRED', name='incident_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('owner_ref', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=64), nullable=True),
    sa.Column('due_state', sa.String(length=64), nullable=True),
    sa.Column('due_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_incidents_machine_id_machines'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('ix_incidents_machine_status', ['machine_id', 'status'], unique=False)

    op.create_table('evidence_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('machine_id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('original_source_record_id', sa.String(length=255), nullable=False),
    sa.Column('original_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('canonical_event_type', sa.String(length=100), nullable=False),
    sa.Column('canonical_payload', sa.JSON(), nullable=False),
    sa.Column('raw_source_payload', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['component_id', 'machine_id'], ['components.id', 'components.machine_id'], name='fk_evidence_events_component_machine', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_evidence_events_machine_id_machines'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_events')),
    sa.UniqueConstraint('source_type', 'original_source_record_id', name='uq_evidence_events_source_original_record')
    )
    with op.batch_alter_table('evidence_events', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_events_component_timeline', ['component_id', 'original_timestamp', 'id'], unique=False)
        batch_op.create_index('ix_evidence_events_ingestion_timestamp', ['ingestion_timestamp'], unique=False)
        batch_op.create_index('ix_evidence_events_machine_timeline', ['machine_id', 'original_timestamp', 'id'], unique=False)
        batch_op.create_index('ix_evidence_events_original_timestamp', ['original_timestamp'], unique=False)

    op.create_table('handover_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('handover_packet_id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['handover_packet_id'], ['handover_packets.id'], name=op.f('fk_handover_items_handover_packet_id_handover_packets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_handover_items_incident_id_incidents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handover_items')),
    sa.UniqueConstraint('handover_packet_id', 'incident_id', name='uq_handover_items_packet_incident')
    )
    with op.batch_alter_table('handover_items', schema=None) as batch_op:
        batch_op.create_index('ix_handover_items_incident_id', ['incident_id'], unique=False)
        batch_op.create_index('ix_handover_items_packet_id', ['handover_packet_id'], unique=False)

    op.create_table('incident_audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('INCIDENT_CREATED', 'EVIDENCE_LINKED', 'EVIDENCE_UNLINKED', 'INCIDENT_SPLIT', 'STATUS_CHANGED', 'OWNER_CHANGED', 'SEVERITY_CHANGED', 'DUE_STATE_CHANGED', 'DUE_TIME_CHANGED', 'RECURRENCE_RECORDED', 'HANDOVER_ACKNOWLEDGED', name='incident_audit_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_audit_events_incident_id_incidents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_audit_events'))
    )
    with op.batch_alter_table('incident_audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_incident_audit_events_incident_timeline', ['incident_id', 'occurred_at', 'id'], unique=False)

    op.create_table('verification_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('verification_rule_id', sa.Uuid(), nullable=False),
    sa.Column('result', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_verification_runs_incident_id_incidents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_rule_id'], ['verification_rules.id'], name=op.f('fk_verification_runs_verification_rule_id_verification_rules'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_runs'))
    )
    with op.batch_alter_table('verification_runs', schema=None) as batch_op:
        batch_op.create_index('ix_verification_runs_incident_lookup', ['incident_id', 'started_at'], unique=False)
        batch_op.create_index('ix_verification_runs_rule_lookup', ['verification_rule_id', 'started_at'], unique=False)

    op.create_table('context_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evidence_event_id', sa.Uuid(), nullable=False),
    sa.Column('quality', sa.Enum('KNOWN', 'UNKNOWN', 'STALE', name='context_quality', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('snapshot_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_event_id'], ['evidence_events.id'], name=op.f('fk_context_snapshots_evidence_event_id_evidence_events'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_context_snapshots'))
    )
    with op.batch_alter_table('context_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_context_snapshots_evidence_event_id', ['evidence_event_id'], unique=False)

    op.create_table('evidence_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evidence_event_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_event_id'], ['evidence_events.id'], name=op.f('fk_evidence_attachments_evidence_event_id_evidence_events'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_attachments'))
    )
    with op.batch_alter_table('evidence_attachments', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_attachments_evidence_event_id', ['evidence_event_id'], unique=False)

    op.create_table('incident_evidence_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_event_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('relationship_type', sa.Enum('RELATED', 'RECURRENCE', 'VERIFICATION', name='incident_evidence_relationship_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('deterministic_rule_identifier', sa.String(length=255), nullable=True),
    sa.Column('link_reason', sa.Text(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('unlinked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(is_active = 1 AND unlinked_at IS NULL) OR (is_active = 0 AND unlinked_at IS NOT NULL)', name=op.f('ck_incident_evidence_links_active_unlinked_timestamp_consistent')),
    sa.ForeignKeyConstraint(['evidence_event_id'], ['evidence_events.id'], name=op.f('fk_incident_evidence_links_evidence_event_id_evidence_events'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_evidence_links_incident_id_incidents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_evidence_links'))
    )
    with op.batch_alter_table('incident_evidence_links', schema=None) as batch_op:
        batch_op.create_index('ix_incident_evidence_links_active_incident', ['incident_id', 'evidence_event_id'], unique=True, sqlite_where=sa.text('is_active = 1'))
        batch_op.create_index('ix_incident_evidence_links_evidence_retrieval', ['evidence_event_id', 'linked_at'], unique=False)
        batch_op.create_index('ix_incident_evidence_links_incident_retrieval', ['incident_id', 'linked_at'], unique=False)

    op.create_table('verification_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('verification_run_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_event_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_event_id'], ['evidence_events.id'], name=op.f('fk_verification_evidence_evidence_event_id_evidence_events'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verification_run_id'], ['verification_runs.id'], name=op.f('fk_verification_evidence_verification_run_id_verification_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_evidence')),
    sa.UniqueConstraint('verification_run_id', 'evidence_event_id', name='uq_verification_evidence_run_evidence')
    )
    with op.batch_alter_table('verification_evidence', schema=None) as batch_op:
        batch_op.create_index('ix_verification_evidence_evidence_event_id', ['evidence_event_id'], unique=False)
        batch_op.create_index('ix_verification_evidence_run_id', ['verification_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_verification_evidence_run_id')
        batch_op.drop_index('ix_verification_evidence_evidence_event_id')

    op.drop_table('verification_evidence')
    with op.batch_alter_table('incident_evidence_links', schema=None) as batch_op:
        batch_op.drop_index('ix_incident_evidence_links_incident_retrieval')
        batch_op.drop_index('ix_incident_evidence_links_evidence_retrieval')
        batch_op.drop_index('ix_incident_evidence_links_active_incident', sqlite_where=sa.text('is_active = 1'))

    op.drop_table('incident_evidence_links')
    with op.batch_alter_table('evidence_attachments', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_attachments_evidence_event_id')

    op.drop_table('evidence_attachments')
    with op.batch_alter_table('context_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_context_snapshots_evidence_event_id')

    op.drop_table('context_snapshots')
    with op.batch_alter_table('verification_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_verification_runs_rule_lookup')
        batch_op.drop_index('ix_verification_runs_incident_lookup')

    op.drop_table('verification_runs')
    with op.batch_alter_table('incident_audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_incident_audit_events_incident_timeline')

    op.drop_table('incident_audit_events')
    with op.batch_alter_table('handover_items', schema=None) as batch_op:
        batch_op.drop_index('ix_handover_items_packet_id')
        batch_op.drop_index('ix_handover_items_incident_id')

    op.drop_table('handover_items')
    with op.batch_alter_table('evidence_events', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_events_original_timestamp')
        batch_op.drop_index('ix_evidence_events_machine_timeline')
        batch_op.drop_index('ix_evidence_events_ingestion_timestamp')
        batch_op.drop_index('ix_evidence_events_component_timeline')

    op.drop_table('evidence_events')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('ix_incidents_machine_status')

    op.drop_table('incidents')
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_index('ix_components_machine_id')

    op.drop_table('components')
    op.drop_table('verification_rules')
    op.drop_table('sync_conflicts')
    op.drop_table('sync_changes')
    op.drop_table('machines')
    with op.batch_alter_table('handover_packets', schema=None) as batch_op:
        batch_op.drop_index('ix_handover_packets_created_at')
        batch_op.drop_index('ix_handover_packets_acknowledged_at')

    op.drop_table('handover_packets')
    # ### end Alembic commands ###
