"""deterministic verification persistence

Revision ID: a4d091e00ba9
Revises: 7c91a2e4f6b8
Create Date: 2026-10-02 17:30:56.960318
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a4d091e00ba9'
down_revision: Union[str, None] = '7c91a2e4f6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('rule_type', sa.Enum('NO_EVENT', name='verification_rule_type', native_enum=False, create_constraint=True), nullable=True))
        batch_op.add_column(sa.Column('window_minutes', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_verification_rules_identifier', ['identifier'])

    with op.batch_alter_table('verification_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('window_ends_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('result',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('SUCCEEDED', 'RECURRENCE_DETECTED', name='verification_run_result', native_enum=False, create_constraint=True),
               existing_nullable=True)
        batch_op.create_index('ix_verification_runs_due_lookup', ['completed_at', 'window_ends_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_verification_runs_due_lookup')
        batch_op.alter_column('result',
               existing_type=sa.Enum('SUCCEEDED', 'RECURRENCE_DETECTED', name='verification_run_result', native_enum=False, create_constraint=True),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('window_ends_at')

    with op.batch_alter_table('verification_rules', schema=None) as batch_op:
        batch_op.drop_constraint('uq_verification_rules_identifier', type_='unique')
        batch_op.drop_column('window_minutes')
        batch_op.drop_column('rule_type')
        batch_op.drop_column('name')
        batch_op.drop_column('identifier')

    # ### end Alembic commands ###
